apiVersion: apps/v1
kind: Deployment
metadata:
  name: dermatology-detector
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dermatology-detector
  template:
    metadata:
      labels:
        app: dermatology-detector
    spec:
      containers:
      - name: dermatology-detector
        image: <your-docker-image>
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: dermatology-detector-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: dermatology-detector
